"""
File tools — save and read markdown solution files.
"""
import os
import re
from datetime import datetime
from pathlib import Path

# Base output directory (relative to project root)
_BASE_DIR = Path(__file__).resolve().parent.parent
SOLUTIONS_DIR = _BASE_DIR / "outputs" / "solutions"
SOLUTIONS_DIR.mkdir(parents=True, exist_ok=True)


def _slugify(text: str, max_len: int = 50) -> str:
    """Convert a string to a safe filename slug."""
    slug = re.sub(r"[^\w\s-]", "", text.lower())
    slug = re.sub(r"[\s_-]+", "_", slug).strip("_")
    return slug[:max_len]


def save_solution_markdown(question: str, domain: str, solution: str) -> str:
    """
    Save a math solution as a well-formatted markdown file.

    Args:
        question: The original math question asked by the student.
        domain:   The math domain (e.g., 'algebra', 'geometry').
        solution: The step-by-step solution text.

    Returns:
        The absolute file path where the solution was saved.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    slug = _slugify(question)
    filename = f"{domain}_{slug}_{timestamp}.md"
    filepath = SOLUTIONS_DIR / filename

    content = f"""# Math Solution: {question}

**Domain:** {domain.capitalize()}  
**Date:** {datetime.now().strftime("%B %d, %Y at %H:%M")}

---

## Problem

> {question}

---

## Step-by-Step Solution

{solution}

---

*Generated by MathViz — Bringing Math to Life Through Animation*
"""

    filepath.write_text(content, encoding="utf-8")
    return str(filepath)


def read_solution_markdown(filepath: str) -> str:
    """
    Read the content of a previously saved solution markdown file.

    Args:
        filepath: Absolute path to the markdown file.

    Returns:
        The full text content of the file.
    """
    path = Path(filepath)
    if not path.exists():
        return f"Error: File not found at {filepath}"
    return path.read_text(encoding="utf-8")


def list_solutions() -> list[dict]:
    """
    List all available solution markdown files.

    Returns:
        A list of dicts with keys: filename, filepath, created_at.
    """
    files = sorted(SOLUTIONS_DIR.glob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True)
    return [
        {
            "filename": f.name,
            "filepath": str(f),
            "created_at": datetime.fromtimestamp(f.stat().st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
        }
        for f in files
    ]
